export const Routes = {
  ONBOARDING: "Onboarding",
  ONBOARDING_HOST: "Onboarding Host",
  MAIN: "Main",
  HOME: "Home",
  VIDEO_FEED: "Video Feed",
  LOGIN: "Login",
  SIGNUP: "Sign Up",
  FORGOT_PASSWORD: "Forgot Password",
  EMAIL_VERIFICATION: "Email Verification",
  RESET_PASSWORD: "Reset Password",
  CHAT: "Chat",
  CHAT_LIST: "Messages",
  CHAT_SEARCH: "Search Chats",
  MESSAGES: "Messages",
  FILTER: "Filter",
  SEARCH: "Search",
  BOOKINGS: "Bookings",
  PROFILE: "Profile",
  PROFILE_HOST: "Profile Host",
  LISTING_DETAILS: "Listing Details",
  ROOM_DETAILS: "Room Details",
  RATINGS: "Ratings",
  AVAILABLE_ROOMS: "Available Rooms",
  SELECT_DATES: "Select Dates",
  CHANGE_DATES: "Change Dates",
  UPDATE_DATES: "Update Dates",
  CANCEL_BOOKING: "Cancel Booking",
  GUEST_INFO: "Guest Info",
  BOOKING_SUMMARY: "Booking Summary",
  BOOKING_DETAILS: "Booking Details",
  PAYMENT_METHOD: "Payment Method",
  RATE_EXPERIENCE: "Rate Your Experience",
  FEEDBACK: "Feedback",
  APP_FEEDBACK: "App Feedback",
  CANCELLATION_FEEDBACK: "Cancellation Feedback",
  MANAGE_ACCOUNT: "Manage Account",
  CHANGE_PASSWORD: "Change Password",
  SAVED: "Saved",
  LIKED: "Liked",
  ONGOING_TAB: "Ongoing",
  COMPLETED_TAB: "Completed",
  RATING_TAB: "To Rate",
  CANCELLED_TAB: "Cancelled",
};
