export const Routes = {
  ONBOARDING: "Onboarding",
  BOTTOM_TABS: "Bottom Tabs",
  HOME: "Home",
  LOGIN: "Login",
  SIGNUP: "Sign Up",
  MESSAGES: "Messages",
  SEARCH_MESSAGES: "Search Messages",
  CHAT: "Chat",
  CART: "Cart",
  FILTER: "Filter",
  SEARCH: "Search",
  BOOKINGS: "Bookings",
  PROFILE: "Profile",
  PROFILE_HOST: "Profile Host",
  LISTING_DETAILS: "Listing Details",
  LISTING_RATINGS: "Listing Ratings",
  ROOM_DETAILS: "Room Details",
  CHECK_AVAILABILITY: "Check Availability",
  SELECT_DATES: "Select Dates",
  GUEST_INFO: "Guest Info",
  BOOKING_SUMMARY: "Booking Summary",
  PAYMENT_METHOD: "Payment Method",
  FEEDBACK: "Feedback",
  MANAGE_ACCOUNT: "Manage Account",
  CHANGE_PASSWORD: "Change Password",
  SAVED: "Saved",
  LIKED: "Liked",
  ONGOING_TAB: "Ongoing",
  COMPLETED_TAB: "Completed",
  RATING_TAB: "To Rate",
  CANCELLED_TAB: "Cancelled",
};
